// Generated by dts-bundle-generator v8.1.1

import { FC } from 'react';
import { ReactDOMServerReadableStream } from 'react-dom/server';

export declare const Build: () => Promise<void>;
export declare const routes: RouteMap;
export type RouteMap = {
	[key: string]: {
		Page: FC<any>;
		GetStream: () => Promise<ReactDOMServerReadableStream>;
	};
};
export declare class Router {
	private routeList;
	constructor();
	add(method: string, pattern: string, handler: Handler): void;
	route(req: Request, headers: {
		"Set-Cookie": string;
		"Content-Type": string;
	}): Promise<Response>;
	match(request: Request): Promise<Response | undefined>;
}
export type URLPatternResultParams = {
	[key: string]: string | undefined;
};
export type Handler = (request: Request, params: URLPatternResultParams, urlPatternResult: URLPatternResult) => Response | Promise<Response>;

export {};
